In [16]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)
x = tf.random.uniform([3, 3])
print("Is there a GPU available: "),
print(tf.config.list_physical_devices("GPU"))
print("Is the Tensor on GPU #0:  "),

print(x.device.endswith('GPU:0'))


TensorFlow version: 2.4.1
Is there a GPU available: 
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Is the Tensor on GPU #0:  
True


In [17]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


In [18]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


In [19]:
predictions = model(x_train[:1]).numpy()
predictions


array([[ 0.07980333,  0.56728494,  0.33331797, -0.51762104,  0.31886405,
        -0.55233836, -0.34089792,  0.14598894,  0.12213394,  0.4741358 ]],
      dtype=float32)

In [20]:
tf.nn.softmax(predictions).numpy()


array([[0.0950558 , 0.15477088, 0.12248381, 0.05230227, 0.12072616,
        0.05051763, 0.06241233, 0.10156   , 0.09916596, 0.14100517]],
      dtype=float32)

In [21]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [22]:
loss_fn(y_train[:1], predictions).numpy()


2.9854326

In [23]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [24]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 1s 543us/step - loss: 0.4803 - accuracy: 0.8593
Epoch 2/5
1875/1875 [==============================] - 1s 541us/step - loss: 0.1537 - accuracy: 0.9538
Epoch 3/5
1875/1875 [==============================] - 1s 547us/step - loss: 0.1086 - accuracy: 0.9686
Epoch 4/5
1875/1875 [==============================] - 1s 532us/step - loss: 0.0851 - accuracy: 0.9750
Epoch 5/5
1875/1875 [==============================] - 1s 539us/step - loss: 0.0707 - accuracy: 0.9774


In [25]:
model.evaluate(x_test,  y_test, verbose=2)


313/313 - 0s - loss: 0.0724 - accuracy: 0.9784


[0.0724346712231636, 0.9783999919891357]

In [26]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [27]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[9.9877351e-09, 1.4891159e-09, 3.6746599e-06, 7.7695309e-05,
        1.1244543e-11, 1.8493868e-08, 1.2743340e-11, 9.9991751e-01,
        3.0436979e-07, 7.5676576e-07],
       [1.8517291e-08, 1.9418732e-04, 9.9974900e-01, 4.9582384e-05,
        1.4108782e-15, 6.8463987e-06, 4.3874696e-08, 4.3551730e-14,
        2.8090102e-07, 1.4032430e-11],
       [8.0492003e-07, 9.9927765e-01, 1.7185110e-04, 1.0462590e-05,
        1.2698319e-05, 1.7934974e-06, 6.3001612e-06, 3.5709632e-04,
        1.6093205e-04, 4.9710144e-07],
       [9.9940300e-01, 3.4033627e-07, 6.8456000e-05, 7.5365034e-07,
        5.9904721e-08, 2.0721254e-05, 4.0880745e-04, 8.0024540e-05,
        1.2785000e-07, 1.7761089e-05],
       [2.1209257e-06, 4.6579398e-09, 9.6086569e-06, 2.7094551e-08,
        9.9636155e-01, 6.2609956e-07, 3.4326918e-06, 2.0999049e-05,
        1.9063580e-06, 3.5997177e-03]], dtype=float32)>

In [28]:
print("Is there a GPU available: "),
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))



Is there a GPU available: 
Num GPUs Available:  1
